{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_employee_module",
    "module": "flutter_release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.0.aar",
          "url": "flutter_release-1.1.0.aar",
          "size": 3826363,
          "sha512": "38d2b1d2258c4f217612483411d808633556fa8a8c0388241c1b1c1e6172163019d2c8205a274455e8ed7d35c6031d630e5078d9db795ec25c79bce8e3d45c17",
          "sha256": "275dc79bbe4c7149152cf10bed3a287936b8cc9b48f25c5553e1cb6c38c77e1a",
          "sha1": "70a79695e1b1401e687b0f06340365e73f06c53e",
          "md5": "2c570924b9fba2179383e4d4d6d3dc6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.0.aar",
          "url": "flutter_release-1.1.0.aar",
          "size": 3826363,
          "sha512": "38d2b1d2258c4f217612483411d808633556fa8a8c0388241c1b1c1e6172163019d2c8205a274455e8ed7d35c6031d630e5078d9db795ec25c79bce8e3d45c17",
          "sha256": "275dc79bbe4c7149152cf10bed3a287936b8cc9b48f25c5553e1cb6c38c77e1a",
          "sha1": "70a79695e1b1401e687b0f06340365e73f06c53e",
          "md5": "2c570924b9fba2179383e4d4d6d3dc6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.0-sources.jar",
          "url": "flutter_release-1.1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.0-javadoc.jar",
          "url": "flutter_release-1.1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
