{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_employee_module",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6128639,
          "sha512": "b64b5076595395a4b388999e2b3f927d9207d4ca5dd2af282ba119f8e3c0478e182c1da8e8fd34d148280d719592d1a8950a9fb9c5803afd716a9010a62f0ec6",
          "sha256": "e2a3c9ca72d3a6d7aa18160fcb00ef145d0b2b6ff6ab5c3276183c81f6b75b06",
          "sha1": "ea6258fefdeeec177033f344150bae2e681b60ab",
          "md5": "1e1d3ab6cf4b27259ed8b7bd231224a2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6128639,
          "sha512": "b64b5076595395a4b388999e2b3f927d9207d4ca5dd2af282ba119f8e3c0478e182c1da8e8fd34d148280d719592d1a8950a9fb9c5803afd716a9010a62f0ec6",
          "sha256": "e2a3c9ca72d3a6d7aa18160fcb00ef145d0b2b6ff6ab5c3276183c81f6b75b06",
          "sha1": "ea6258fefdeeec177033f344150bae2e681b60ab",
          "md5": "1e1d3ab6cf4b27259ed8b7bd231224a2"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 261687,
          "sha512": "e1a6d33dda75d144f4e55191c618680bb96eaa38d844a6997ae3c2636b285645deb0b086688b72e6f364ace0729f67f8cc5e1f7299e04b1543dd49d0c30411a3",
          "sha256": "d9aa77c8f41815c9159984c3501460f6dfc6604ab5916a8ee4e35dee3c346d16",
          "sha1": "2166d022d582188b28e846f39b36a1082b5f9066",
          "md5": "7c80635e3e18a560f1391d955845529e"
        }
      ]
    }
  ]
}
