{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_employee_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 16909831,
          "sha512": "4218c89473a6f91225f41baedf44eee7d7c903c8a5ad6c0d730a727b591445e43f0dcbf9f585c53eb8f088dba2dbbc3fb6032d522f1fd4aea23ffd434579a09f",
          "sha256": "e646219c8eb390f4c9fe9decb78ba751f4e6e148bb0c201c9d7e04ac5f5a3325",
          "sha1": "a1f1486e07693ddec05d1b452ef6e4245f3e4a00",
          "md5": "328e8efa2378db73d8eb39abb2ee9db5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-052f31d115eceda8cbff1b3481fcde4330c4ae12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 16909831,
          "sha512": "4218c89473a6f91225f41baedf44eee7d7c903c8a5ad6c0d730a727b591445e43f0dcbf9f585c53eb8f088dba2dbbc3fb6032d522f1fd4aea23ffd434579a09f",
          "sha256": "e646219c8eb390f4c9fe9decb78ba751f4e6e148bb0c201c9d7e04ac5f5a3325",
          "sha1": "a1f1486e07693ddec05d1b452ef6e4245f3e4a00",
          "md5": "328e8efa2378db73d8eb39abb2ee9db5"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 261687,
          "sha512": "e1a6d33dda75d144f4e55191c618680bb96eaa38d844a6997ae3c2636b285645deb0b086688b72e6f364ace0729f67f8cc5e1f7299e04b1543dd49d0c30411a3",
          "sha256": "d9aa77c8f41815c9159984c3501460f6dfc6604ab5916a8ee4e35dee3c346d16",
          "sha1": "2166d022d582188b28e846f39b36a1082b5f9066",
          "md5": "7c80635e3e18a560f1391d955845529e"
        }
      ]
    }
  ]
}
